github:
  - JounQin
  - 1stG
  - rx-ts
  - un-ts
patreon: 1stG
open_collective: eslint-plugin-prettier
custom:
  - https://opencollective.com/1stG
  - https://opencollective.com/rxts
  - https://opencollective.com/unts
  - https://afdian.net/@JounQin
