name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    name: Lint and Test on Node ${{ matrix.node }} (ESLint ${{ matrix.eslint }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [24, 22, 20]
        eslint: [10, 9, 8]
        include:
          - { node: 18, eslint: 9 }
          - { node: 18, eslint: 8 }
          - { node: 16, eslint: 8 }
          - { node: 14, eslint: 8 }

    steps:
      - name: Checkout Repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install
        run: pnpm install --prefer-frozen-lockfile

      - name: Install ESLint ${{ matrix.eslint }}
        run: pnpm upgrade eslint@${{ matrix.eslint }}

      - name: Install older transitive dependencies for ESLint 9
        if: ${{ matrix.eslint == 9 }}
        run: pnpm upgrade @eslint/js@9 @eslint/json@0.14

      - name: Install older transitive dependencies for ESLint 8
        if: ${{ matrix.eslint == 8 }}
        run: pnpm upgrade @eslint/js@9 @eslint/json@0.14 @graphql-eslint/eslint-plugin@3 eslint-plugin-svelte@2 svelte@3 vue-eslint-parser@9

      - name: Test
        run: pnpm mocha

      - name: Perf
        # Skip syntax errors or unavailable features on older Node.js versions
        if: ${{ matrix.node >= 20 }}
        run: TIMING=1 pnpm lint
