name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    name: Lint and Test on Node ${{ matrix.node }} (ESLint ${{ matrix.eslint }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node:
          - 26
          - 24
          - 22
          - 20
        eslint:
          - 10
          - 9
          - 8
        include:
          - node: 18
            eslint: 9
          - node: 18
            eslint: 8
          - node: 16
            eslint: 8
          - node: 14
            eslint: 8

    steps:
      - name: Checkout Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node }}

      - name: Enable Corepack
        run: |
          corepack --version >/dev/null 2>&1 || npm install -g corepack
          corepack enable

      - name: Adapt for Yarn 3 on older Node.js
        if: ${{ matrix.node < 18 }}
        run: |
          jq '.packageManager = "yarn@3.8.7" | .resolutions["webcrypto-core"] = "~1.8.1"' package.json > package.json.tmp && mv package.json.tmp package.json
          rm -f yarn.lock

      - name: Install
        run: yarn install --${{ matrix.node < 18 && 'no-' || '' }}immutable

      - name: Install older graphql/mocha for older Node.js versions
        if: ${{ matrix.node < 20 }}
        run: yarn up graphql@16 mocha@11

      - name: Install ESLint ${{ matrix.eslint }}
        run: yarn up eslint@${{ matrix.eslint }}

      - name: Install older transitive dependencies for ESLint 9
        if: ${{ matrix.eslint == 9 }}
        run: yarn up @eslint/js@9 @eslint/json@0.14

      - name: Install older transitive dependencies for ESLint 8
        if: ${{ matrix.eslint == 8 }}
        run: |
          yarn add -D @types/eslint@8
          yarn up @eslint/js@9 @eslint/json@0.14 @graphql-eslint/eslint-plugin@3 eslint-plugin-svelte@2 svelte@3 vue-eslint-parser@9

      - name: Test
        run: yarn mocha

      - name: Perf
        # Skip syntax errors or unavailable features on older Node.js versions
        if: ${{ matrix.node >= 20 }}
        run: TIMING=1 yarn lint
